conn SALESAMPLE/SALESAMPLE

insert into TR_SALES_OUTLINE values(TR_SALES_OUTLINE_SALES_ID_SEQ.NEXTVAL,'C0000001','u003',sysdate);
insert into TR_SALES_DETAIL values(TR_SALES_DETAIL_DETAIL_ID_SEQ.NEXTVAL,TR_SALES_OUTLINE_SALES_ID_SEQ.CURRVAL,'00000001',1,3000);
insert into TR_SALES_DETAIL values(TR_SALES_DETAIL_DETAIL_ID_SEQ.NEXTVAL,TR_SALES_OUTLINE_SALES_ID_SEQ.CURRVAL,'00000004',2,100);

insert into TR_SALES_OUTLINE values(TR_SALES_OUTLINE_SALES_ID_SEQ.NEXTVAL,'C0000002','u004',sysdate);
insert into TR_SALES_DETAIL values(TR_SALES_DETAIL_DETAIL_ID_SEQ.NEXTVAL,TR_SALES_OUTLINE_SALES_ID_SEQ.CURRVAL,'00000005',1,1000);
insert into TR_SALES_DETAIL values(TR_SALES_DETAIL_DETAIL_ID_SEQ.NEXTVAL,TR_SALES_OUTLINE_SALES_ID_SEQ.CURRVAL,'00000006',10,900);


commit;